// Generated by https://quicktype.io

export interface IOrdenResponse {
  fecha: string;
  hora: string;
  total: number;
  tipoPago: string;
  usuario: IUsuarioOrden;
  detallesOrdenes: IDetalleOrdene[];
  stripeChargeId: string;
  id: number;
}

export interface IDetalleOrdene {
  cantidad: number;
  medicamento: IMedicamentoOrden;
  id: number;
}

export interface IUsuarioOrden {
  id: number;
}

export interface IMedicamentoOrden {
  id: number;
}

// End orden lista

// Generated by https://quicktype.io

export interface IOrdenFullResponse {
  fecha: string;
  total: number;
  usuario: IUsuarioDetalleFull;
  detallesOrdenes: IDetalleOrdenFull[];
}

export interface IDetalleOrdenFull {
  cantidad: number;
  medicamento: IMedicamentoDetalleFUll;
}

export interface IMedicamentoDetalleFUll {
  nombre: string;
  precio: number;
  imagen: string;
  farmacia: IFarmaciaDetalleFull;
}

export interface IFarmaciaDetalleFull {
  nombre: string;
}

export interface IUsuarioDetalleFull {
  nombre: string;
  apellidoPaterno: string;
  apellidoMaterno: string;
}
